# Nombre del servicio para el API Gateway
spring.application.name=api-gateway
server.port=8081
# Puerto en el que estará corriendo el API Gateway

# Configuración de Eureka Discovery Client
#spring.cloud.discovery.enabled=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#
## Habilitar el descubrimiento automático de servicios para rutas
#spring.cloud.gateway.discovery.locator.enabled=true
#
#spring.cloud.config.enabled=false
#
## Configuración de Spring Cloud Gateway
#spring.cloud.gateway.routes[0].id=users-service
#spring.cloud.gateway.routes[0].uri=lb://users-management-system
#spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**
#
#spring.cloud.gateway.routes[1].id=service-service
#spring.cloud.gateway.routes[1].uri=lb://service-management-system
#spring.cloud.gateway.routes[1].predicates[0]=Path=/services/**
#
#spring.cloud.gateway.routes[2].id=appointment-service
#spring.cloud.gateway.routes[2].uri=lb://appointment-management-system
#spring.cloud.gateway.routes[2].predicates[0]=Path=/appointments/**
#
#spring.cloud.gateway.routes[3].id=review-service
#spring.cloud.gateway.routes[3].uri=lb://review-management-system
#spring.cloud.gateway.routes[3].predicates[0]=Path=/reviews/**
#
#spring.cloud.gateway.routes[4].id=payment-service
#spring.cloud.gateway.routes[4].uri=lb://payment-management-system
#spring.cloud.gateway.routes[4].predicates[0]=Path=/payments/**
#
#spring.cloud.gateway.routes[5].id=notification-service
#spring.cloud.gateway.routes[5].uri=lb://notification-management-system
#spring.cloud.gateway.routes[5].predicates[0]=Path=/notifications/**
